name: snaplint
version: '0.2'
summary: Clean up your snaps
description: |
  Snaplint is a tool which scans your snap and points out rule and policy
  violations.
  It comes with a default set of rules which look for copyright information,
  leftover development files, and unneeded libraries. It can also be easily
  extended with custom rules that fit your development policies.

grade: stable
confinement: strict

apps:
    snaplint:
        command: snaplint
        plugs: [home]

parts:
  snaplint:
    plugin: python
    source: .
    stage-packages:
        - python3-pyelftools
